# Sendinblue example config.
sendinblue:
    api_key: 'XXXXXXXXXXXXXXXXXXXXXXX-us5' # Your sendinblue api key.
    campaigns:
        dailyNewsletterCampaign:
            list_id: 12345 # Id of your newsletter list.
