# Sendinblue example config.
sendinblue:
    api_key: 'XXXXXXXXXXXXXXXXXXXXXXX-us5' # Your sendinblue api key.
    #campaigns:
    #    dailyNewsletterCampaign:
    #        list_id: 12345 # ID of your newsletter list.
    #        doi_template_id: 123 # ID of your double opt-in template.
